# Generated by Django 5.2.4 on 2025-08-04 03:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publish_date",
            new_name="publish",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=250,
                populate_from="title",
                unique_for_date="publish",
            ),
        ),
    ]
