# Generated by Django 5.2.4 on 2025-08-04 03:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_publish_date_post_publish_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", unique_for_date="publish"
            ),
        ),
    ]
