# Generated by Django 5.2.4 on 2025-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish"]},
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(null=True),
        ),
    ]
