# Generated by Django 5.2.4 on 2025-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
